#!/bin/bash

# Shortcut for debugging without fuss

if [[ "$1" == "" ]]
then
	echo "Use $0 application and arguments to run it through gdb"
	exit 1
fi

TEMPDIR=~/tmp

# Set up a command file for gdb so you won't need to type backtrace and quit, but directly run gdb without user interaction
mkdir -p $TEMPDIR
echo 'run' > $TEMPDIR/gdb.cmds; echo 'bt' >> $TEMPDIR/gdb.cmds; echo 'quit' >> $TEMPDIR/gdb.cmds;

# The gdb command syntax
RUN="gdb -x $TEMPDIR/gdb.cmds --args "

# Run it through gdb with all arguments
$RUN $@
